name: Publish
description: Publish to npm

inputs:
  token:
    description: 'npm token'
    required: true

runs:
  steps:
    # see https://github.com/google-github-actions/release-please-action#automating-publication-to-npm
    # see https://docs.npmjs.com/generating-provenance-statements
    - name: Checkout Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 24.6.0
        registry-url: https://registry.npmjs.org
    - name: Install & Build
      uses: bahmutov/npm-install@3714964fb879ebbbc108e167f0f3a0c81ec075c9 # v1.10.10
    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
      run: npm publish --provenance --access public --registry https://registry.npmjs.org
      shell: bash
  using: composite
