name: Publish
description: Publish to npm

inputs:
  token:
    description: 'npm token'
    required: true

runs:
  steps:
    # see https://github.com/google-github-actions/release-please-action#automating-publication-to-npm

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0

    - name: Install & Build
      uses: bahmutov/npm-install@6bbff949458c1dd99b20e185cee8c4d6fcf1212a # v1.10.9

    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{inputs.token}}
      run: npm publish --provenance --access public --registry https://registry.npmjs.org
      shell: bash
  using: composite
